### ISSUE TITLE
signatures file compression

### ISSUE THREAD

**Issue by catalinberta** [marrone/grunt-tinypng#10]
Is there any way to make the signatures json file to be written in an uncompressed format? Currently it adds everything in one line (compressed) which makes conflicts difficult to solve.

Thanks in advance!

**Comment by marrone** [comment]
I've added a new option to support this, see the updated README
You can now use, for example, `sigFileSpace:4` as an extra option to pretty print. See the MDN docs on JSON.stringify for more examples
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_space_argument
