### ISSUE TITLE
.jpg with tinyjpg

### ISSUE THREAD

**Issue by evamichalcak** [marrone/grunt-tinypng#17]
Does this task process .jpg images too? 
If yes, how would the compress task options look for compressing both .jpg and .png?
If not, could that be added (since the tinypng API can process .jpg)?

**Comment by HugoHeneault** [comment]
Yes it does. 

Here's how I achieve it:

````js
tinypng: {
	options: {
		// Some options
	},
	compress: {
		expand: true,
		src: ['**/*.{png,jpg,jpeg}'],
		cwd: 'src/img/',
		dest: 'img'
	}
},
````

**Comment by marrone** [comment]
I've added a new test that compresses a jpg, you can verify via `grunt test`
