### ISSUE TITLE
Can't access to tinypng.com with a proxy

### ISSUE THREAD

**Issue by AsoWeb** [marrone/grunt-tinypng#21]
I have a proxy on my server and grunt-tinypng does not work with a proxy.

I had to edit the plugin by adding an agent (with https-proxy-agent) and also modify the code for the method downloadOutputImage:

var opt = {
					host: urlInfo.hostname,
					path: urlInfo.pathname,
					method: 'GET',
					accepts: '*/*',
					rejectUnauthorized: false,
					requestCert: true,
					agent: agent
				};
https.get(opt, function(imageRes) {...

You can change your code to handle a proxy?

Thank you

**Comment by marrone** [comment]
Resolved by f56b8c9f53ace8119f6f05328130ca067822b3a7

**Comment by nktka** [comment]
Are you planning on making this change part of a new release, so the feature is available through npm?
